### ISSUE TITLE
制板的时候的问题

### ISSUE THREAD

**Issue by Zyilin98** [liaozhelin/yds-charger#1]
找jlc制顶板的时候 被嘉立创告知无法制版 需要修改图纸
![8O29X(E%4}3}LWVDXBH2E05](https://user-images.githubusercontent.com/61766598/170805423-e5c73dda-33f9-4c21-aa52-46276633e090.png)
这个是直接告啥嘉立创直接做 还是需要硬件部分迭代

**Comment by Zyilin98** [comment]
顺便老哥 你传个LICENSE文件到GitHub上 保证一下开源协议 省的被人直接扒走

**Comment by liaozhelin** [comment]
你好，这个直接标注强制生产即可（断板不补就行），后续我会修改一版，去掉这些细连接处，尽可能降低生产的难度

**Comment by liaozhelin** [comment]
> 顺便老哥 你传个LICENSE文件到GitHub上 保证一下开源协议 省的被人直接扒走

好的谢谢提醒，我资料还没上传完，等弄好把license也整上

**Comment by Zyilin98** [comment]
![image](https://user-images.githubusercontent.com/61766598/170805929-6053126b-ab80-4281-9ba1-abaa69492bbc.png)
ma'le麻了 给他说了直接做就行 断了就断了 结果还不行 我好佩服嘉立创这么敬业

**Comment by liaozhelin** [comment]
> ![image](https://user-images.githubusercontent.com/61766598/170805929-6053126b-ab80-4281-9ba1-abaa69492bbc.png)
> ma'le麻了 给他说了直接做就行 断了就断了 结果还不行 我好佩服嘉立创这么敬业

好家伙，我之前打样了不下5次都没有问题，现在居然变严格了，那我后面改一版本去掉这些细的边框看看，就是有可能变四层板，有些线走不出来了hh，你可以换个号试试看，只要不触发人工审核一般都可以通过

**Comment by Zyilin98** [comment]
我现在下单全都是 人工审核 不管换哪个号 属实是麻中麻

**Comment by liaozhelin** [comment]
> 

看来审核规则改了hhh，那我后面改个板子，这个是上层板就是一些转接的功能，你可以先做下层板，备料还是需要些时间的hh

**Comment by Zyilin98** [comment]
好的 感谢 先把下层做了吧 上层等迭代吧

**Comment by liaozhelin** [comment]
已经提交上层迭代版本

**Comment by Zyilin98** [comment]
麻了 老哥你能把 pcb文件私法我一份 我改一下么 今天我又被jlc认为是拼单了 让他生产 就叫我补全款 换个号也这样 麻了

**Comment by liaozhelin** [comment]
嘉立创打样成功的人不少欸，现在可能打样的人太多了，可以试一下华秋和捷配，这两个也是免费打样，华秋是四层板刚好可以，你邮箱也发我个哈

**Comment by Zyilin98** [comment]
> 嘉立创打样成功的人不少欸，现在可能打样的人太多了，可以试一下华秋和捷配，这两个也是免费打样，华秋是四层板刚好可以，你邮箱也发我个哈，实在不行我再改下发你 ![](https://raw.githubusercontent.com/liaozhelin/picgo/master/QQ%E6%88%AA%E5%9B%BE20220530120053.jpg)

Zyilin98@gmail.com

**Comment by liaozhelin** [comment]
资料已发

**Comment by Zyilin98** [comment]
老哥，就是关于esp的接口那里 能不能做个直插式的焊盘 这样也方便焊排针？

**Comment by QGB** [comment]
0 C:/test/jlc-eda/hqdfm_hqdl_wz.zip       <76.868 MiB> c39a170fac7e5c70a4e15cb5e3b8f759 7de4cede0c139a28a684beb1d50a0c6915c6ac9bbfe5cffb7e195cd4865488d1
 {'C:/test/jlc-eda/hqdfm_hqdl_wz.zip': [<76.868 MiB>, <2022-10-30__13.30.29__.970>, <2022-10-30__13.30.29__.970>, <2022-10-30__13.29.59__.064>, <0o100666>]}
