### ISSUE TITLE
寄了 电脑认不到板子，串口也不认

### ISSUE THREAD

**Issue by Zyilin98** [liaozhelin/yds-charger#10]
反正是历尽千辛万苦终于做出来一个版本 然后 3.3Vdc-dc电路哪里也正常出了3.3V 但是led没一个亮的 双sw3526也没有输出 倒是A口哪里开始有输出了 
接电脑 不管是usb直通 （3.3V已经提供了）还是用ch340通过串口连接 设备基本上就认不到 本来我以为是上层版没做的原因 做了顶层版 按着波动开关还是不认  我已经麻了 实在是不知道哪里的问题导致电脑不认esp32了 显示屏还没焊 怕万一esp32烧了 显示屏一块带走 损失更大

**Comment by liaozhelin** [comment]
led在没有烧程序的时候亮是正常的，至于不认芯片，这个电脑是提示无法识别的设备，还是什么提示都没有？

**Comment by Zyilin98** [comment]
> led在没有烧程序的时候不亮是正常的，至于不认芯片，这个电脑是提示无法识别的设备，还是什么提示都没有？ 主控芯片是否买的有内置flash版本的c3fn4？

电脑什么提示都没有 设备管理器连弹窗都没有 买的是ESP32-C3FH4

**Comment by liaozhelin** [comment]
> > led在没有烧程序的时候不亮是正常的，至于不认芯片，这个电脑是提示无法识别的设备，还是什么提示都没有？ 主控芯片是否买的有内置flash版本的c3fn4？
> 
> 电脑什么提示都没有 设备管理器连弹窗都没有 买的是ESP32-C3FH4

方便提交下你的焊接完的板子和连线照片嘛？

**Comment by Zyilin98** [comment]
![微信图片_20220614124538](https://user-images.githubusercontent.com/61766598/173495095-cfbd8485-89a2-4dd9-b461-b2e3360abcea.jpg)
![微信图片_20220614124527](https://user-images.githubusercontent.com/61766598/173495099-805c5e6d-c340-478e-a4d4-72b7dad67219.jpg)

**Comment by Zyilin98** [comment]
还没来得及洗板子.....

**Comment by liaozhelin** [comment]
> 还没来得及洗板子.....

目前我所看到的器件应该都正常，可能还是要重点检查下USB DM DP这两个到芯片的焊接是否虚焊

**Comment by Zyilin98** [comment]
去量了 出了一个0.15V 然后Q2 Q3这个Si2309 D极只有0.15V的电压 然后Q4 LMBT3904DW1T1G 除了从E_1 E_2这里有高电压 剩下的位置对地基本上没什么电压

**Comment by Zyilin98** [comment]
再去看了一下 要么是esp32挂了 要么就是虚焊 因为3.3的电路都蛮好的  我感觉虚焊可能性不高 因为已经尝试过加焊了 拆下来的时候焊盘也没连锡

**Comment by liaozhelin** [comment]
> 再去看了一下 要么是esp32挂了 要么就是虚焊 因为3.3的电路都蛮好的 我感觉虚焊可能性不高 因为已经尝试过加焊了 拆下来的时候焊盘也没连锡

是的，如果手头有空余芯片可以替换下看看

**Comment by gzzz2008** [comment]
我也出现这种情况，链接电脑没有任何反应，最后怎么解决的呢？

**Comment by Zyilin98** [comment]
> 我也出现这种情况，链接电脑没有任何反应，最后怎么解决的呢？

第一个检查3.3V供电有没有出 有了就检查C15的电压是不是3.3V 如果两个都是 还是不认 检查usb接口焊接 和接口定义是不是接错了
然后检查晶振是不是正常工作 是不是正常起振  如果还是不行 就直接换个esp32吧

**Comment by gzzz2008** [comment]
没有示波器怎么检查晶振呢？

**Comment by Zyilin98** [comment]
> 没有示波器怎么检查晶振呢？

第一个你的晶振得是无源晶振 第二个晶振有四个触点 看四个触点的定义是不是跟pcb上的一样(就是你有没有焊反了)
第三个就是检查有没有起振 这个是必须要示波器的
第第四 看看c15这个电容有没有对地3.3的电压 有才能算esp32可能正常工作 如果没有就esp32根本没有工作
