### ISSUE TITLE
电感的型号

### ISSUE THREAD

**Issue by Albertdeng23** [liaozhelin/yds-charger#102]
我想问一下“22uH功率电感”这个元件的型号/购买渠道，我在嘉立创和淘宝之类的地方没有找到类似的元件。
开发者在做实物的时候选料是在哪里选的？
（即为图中的L1）
![IMG_20240226_141714](https://github.com/liaozhelin/yds-charger/assets/99789195/b9682c0d-2548-48db-aff3-09d65fa091af)

**Comment by HelloWorld-oO** [comment]
【淘宝】https://m.tb.cn/h.5vflgwAMALCdmXp?tk=ClXLWlnOxMZ CZ0016 「CEP147NP-6R1 CEP1411NP-100 CEP1411NP-140 CEP1411NP-180」
点击链接直接打开 或者 淘宝搜索直接打开

**Comment by HelloWorld-oO** [comment]
> 【淘宝】https://m.tb.cn/h.5vflgwAMALCdmXp?tk=ClXLWlnOxMZ CZ0016 「CEP147NP-6R1 CEP1411NP-100 CEP1411NP-140 CEP1411NP-180」 点击链接直接打开 或者 淘宝搜索直接打开

选择  220 新   这一项
