### ISSUE TITLE
10pf的0603电容电压应该是多少v呢 我找了许多只有50v的

### ISSUE THREAD

**Issue by Tomoneplus** [liaozhelin/yds-charger#11]

**Comment by liaozhelin** [comment]
是两个晶振的匹配电容吗，这个无所谓，买耐压最低的就行，有要求耐压的电容是电源主线上的电容

**Comment by Tomoneplus** [comment]
还有0.1uf的也是只有50v

**Comment by liaozhelin** [comment]
> 还有0.1uf的也是只有50v

0.1uf的电容一般买25V的就可以

**Comment by Tomoneplus** [comment]
0.1uf 25v的可以发个连接吗 我找了好多都是50v的

**Comment by liaozhelin** [comment]
> 0.1uf 25v的可以发个连接吗 我找了好多都是50v的

可以买50V的，没有问题

**Comment by Tomoneplus** [comment]
找到了 1uf25v 105k

**Comment by liaozhelin** [comment]
> 找到了 1uf25v 105k

嗯嗯，除了输入总线上的电容外其他电容无需太过在乎耐压值
