### ISSUE TITLE
大佬你好

### ISSUE THREAD

**Issue by Sirius-Cooper** [liaozhelin/yds-charger#12]
大佬你好，我现在做好了，充电啥的功能也实现了，但是WIFI配网完成以后那个气象站不显示，请问这是正常的嘛，还有我想问一下有OTA升级时选中自动更新会是什么反应

**Comment by liaozhelin** [comment]
是的，气象站的API还在开发中，因为目前用的个人天气API无法给多人使用，所以先屏蔽了，正在搞服务转发中。OTA升级中的自动更新还未写功能，后续实现的功能就是每天轮询，查询到新固件版本后自动更新。

**Comment by Sirius-Cooper** [comment]
好的，感谢大佬
