### ISSUE TITLE
原理图源文件如何打开

### ISSUE THREAD

**Issue by Gonglja** [liaozhelin/yds-charger#13]
哈喽，大佬好，想换点器件，将65w升级为100w，请问原理图源文件是哪个？那个json文件吗？
如方便，告知下软件

**Comment by liaozhelin** [comment]
> 哈喽，大佬好，想换点器件，将65w升级为100w，请问原理图源文件是哪个？那个json文件吗？
> 
> 如方便，告知下软件

使用lceda打开，换成100w的话可能得重新方案选型才行，这个体积可能不好塞的下

**Comment by Gonglja** [comment]
> > 哈喽，大佬好，想换点器件，将65w升级为100w，请问原理图源文件是哪个？那个json文件吗？
> > 如方便，告知下软件
> 
> 使用lceda打开，换成100w的话可能得重新方案选型才行，这个体积可能不好塞的下

好的，感谢，芯片目前考虑 3519、3518s，顺便换一下彩屏

**Comment by Gonglja** [comment]
up您好
看了下里面没有pcb文件，方便发下嘛，需要改下设计
我的邮箱是 glj0艾特outlook.com

**Comment by liaozhelin** [comment]
> up您好 看了下里面没有pcb文件，方便发下嘛，需要改下设计 我的邮箱是 glj0艾特outlook.com

PCB文件目前暂时不公开哈，可以根据开放的原理图文件自己画，体积增大两层板可以搞定

**Comment by Gonglja** [comment]
好的，那我这边设计一下，感谢
