### ISSUE TITLE
SW3526

### ISSUE THREAD

**Issue by Sirius-Cooper** [liaozhelin/yds-charger#14]
大佬你好，我U1的SW3526输入12V时可以正常工作，但是输入24V时接手机充电，电压就会一直快速的在5V和0V之前跳变，然后手机显示也是一直处于充电和未充电两个状态跳变。U2的SW3526是完全可以拉满正常使用的，我想问一下这大概会是什么问题，是芯片坏掉了吗还是电容耐压值不够，求解

**Comment by liaozhelin** [comment]
> 大佬你好，我U1的SW3526输入12V时可以正常工作，但是输入24V时接手机充电，电压就会一直快速的在5V和0V之前跳变，然后手机显示也是一直处于充电和未充电两个状态跳变。U2的SW3526是完全可以拉满正常使用的，我想问一下这大概会是什么问题，是芯片坏掉了吗还是电容耐压值不够，求解

我觉得应该是焊接问题或者采样电阻吧，如果是有一组可以的话应该是有问题的那一组检测到过流触发保护之类的

**Comment by Sirius-Cooper** [comment]
好的我试试采样电阻喝重新焊接
