### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ChinaCKKK** [liaozhelin/yds-charger#15]
up主您好
已经着手复刻您的项目了，遇到一点问题：3.3V DCDC稳压电路，RY8411芯片反馈电容是使用多大的呢，您的原理图上标注为NC，但是看您发的b站视频，是焊接上了的，所以特此请教up主，望解答，谢谢

**Comment by liaozhelin** [comment]
这个可以焊接一个20p的电容，但是影响不大，所以我在bom中去掉了，环路我用示波器看还是挺稳定的

**Comment by ChinaCKKK** [comment]
收到，谢谢up主，回复效率太高了，太感谢了
后续有问题可能还要叨扰您，再次感谢，视频已三连！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liaozhelin/yds-charger"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月15日(星期三) 晚上9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liaozhelin/yds-charger] question (Issue #15)





 
这个可以焊接一个20p的电容，但是影响不大，所以我在bom中去掉了，环路我用示波器看还是挺稳定的

**Comment by liaozhelin** [comment]
谢谢，仓库中的信息有邮件提醒所以回复比较及时，后续制作中有啥问题再交流哈👀

**Comment by ChinaCKKK** [comment]
up主你好，我今天开始下载固件了，遇到点问题：3.3v供电正常，使用的USB转TTL，把上面的器件全都卸下来了，使用杜邦线直接焊接上去的，连接板子的时候只连接了DP和GND，VCC并未连接（5V会烧esp32），然后板子使用DC供电，但是电脑并未成功识别




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liaozhelin/yds-charger"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月15日(星期三) 晚上9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liaozhelin/yds-charger] question (Issue #15)





 
谢谢，仓库中的信息有邮件提醒所以回复比较及时，后续制作中有啥问题再交流哈👀

**Comment by liaozhelin** [comment]
连接板子的时候只连接了DP和GND？是少打了嘛？

**Comment by ChinaCKKK** [comment]
我就是只连接了中间两根数据线和GND，然后插上电脑，没有反应，已经重新换了一颗芯片了，还是这样，C15电容只有1.2V电压，3.3V供电正常




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liaozhelin/yds-charger"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月16日(星期四) 上午9:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liaozhelin/yds-charger] question (Issue #15)





 
连接板子的时候只连接了DP和GND？是少打了嘛？

**Comment by liaozhelin** [comment]
重点检查下晶振得焊接，可以去掉晶振两个匹配电容试试，C15为1.5v说明芯片没有正常启动

**Comment by ChinaCKKK** [comment]
我是这样接线的，不知道这样对不对


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liaozhelin/yds-charger"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月16日(星期四) 上午9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liaozhelin/yds-charger] question (Issue #15)





 
重点检查下晶振得焊接，可以去掉晶振两个匹配电容试试，C15为1.5v说明芯片没有正常启动

**Comment by galamygod** [comment]
老哥，我把6525换成了6505，现在上电9v有七百毫安，去掉u3有一百多毫安，连接dp和dm电脑一点反应没有

**Comment by galamygod** [comment]
我又换了一个6505（u8），现在电压9v，电流为16毫安，但是连接电脑没反应，是我驱动问题吗

**Comment by galamygod** [comment]
现在排查出的问题就是只要装上u3就会大电流

**Comment by liaozhelin** [comment]
> 现在排查出的问题就是只要装上u3就会大电流

IP6525的和连接电脑关系不大，你最好检查一下IP6525和IP6505是不是可以pintopin替换的，正常待机电流在12V时候应该是在30mA左右，驱动的话我仓库里有，得安装才行

**Comment by liaozhelin** [comment]
> 老哥，我把6525换成了6505，现在上电9v有七百毫安，去掉u3有一百多毫安，连接dp和dm电脑一点反应没有

重点检查是否有虚焊，以及晶振电路和电源电路，满足这两个条件应该就可以检测到

**Comment by liaozhelin** [comment]
> 我是这样接线的，不知道这样对不对
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "liaozhelin/yds-charger" ***@***.***&gt;; 发送时间:&nbsp;2022年6月16日(星期四) 上午9:38 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [liaozhelin/yds-charger] question (Issue #15) 重点检查下晶振得焊接，可以去掉晶振两个匹配电容试试，C15为1.5v说明芯片没有正常启动 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好像没看到您是怎么接线的，主要应该还是上面所说的那些问题

**Comment by ChinaCKKK** [comment]
好的，我再去检查检查。大三考研党，没啥时间专门弄这个，也就是闲余时间弄一下。感谢up主




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liaozhelin/yds-charger"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月17日(星期五) 晚上6:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liaozhelin/yds-charger] question (Issue #15)





  
我是这样接线的，不知道这样对不对
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "liaozhelin/yds-charger" @.&gt;; 发送时间:&nbsp;2022年6月16日(星期四) 上午9:38 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [liaozhelin/yds-charger] question (Issue #15) 重点检查下晶振得焊接，可以去掉晶振两个匹配电容试试，C15为1.5v说明芯片没有正常启动 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
好像没看到您是怎么接线的，主要应该还是上面所说的那些问题

**Comment by galamygod** [comment]
> > 老哥，我6525换成6505，现在上电9v有七百毫安，把u3有一百多毫安删除，连接dp和dm电脑一点反应没有
> 
> 重点检查是否有虚焊，以及晶振电路和电源电路，满足这两个条件应该就可以检测到

电源电路是没有问题的，3.3已经有了，我是用dc供电，然后USB中间两条接到板子上，驱动我双击以后会闪退，我也不知道安装成功没有

**Comment by liaozhelin** [comment]
> > > 老哥，我6525换成6505，现在上电9v有七百毫安，把u3有一百多毫安删除，连接dp和dm电脑一点反应没有
> 
> > 
> 
> > 重点检查是否有虚焊，以及晶振电路和电源电路，满足这两个条件应该就可以检测到
> 
> 
> 
> 电源电路是没有问题的，3.3已经有了，我是用dc供电，然后USB中间两条接到板子上，驱动我双击以后会闪退，我也不知道安装成功没有

如果双击闪退，可以去官网下载自己平台的对应驱动，以管理员模式运行
