### ISSUE TITLE
boom配件，与

### ISSUE THREAD

**Issue by rambodoctor** [liaozhelin/yds-charger#18]
大佬，请问active boom 的文件该如何使用，小小白正打算复刻你的作品，板子完成打样，正在为boom 的问题发愁  ，另外怎么知道pcb上放置该哪些电容电阻件嘛。  另外大佬如果需要服务器存放升级文件，或者转发天气什么的 ， 我可以提供一台服务器，也可以帮忙采集天气。

**Comment by liaozhelin** [comment]
> 大佬，请问active boom 的文件该如何使用，小小白正打算复刻你的作品，板子完成打样，正在为boom 的问题发愁  ，另外怎么知道pcb上放置该哪些电容电阻件嘛。  另外大佬如果需要服务器存放升级文件，或者转发天气什么的 ， 我可以提供一台服务器，也可以帮忙采集天气。

你好，动态bom直接浏览器打开就可以使用了，至于怎么摆放器件就是根据bom就可以了，看位号。服务器的话我自己有，正在开发中，感谢你的好意了～
