### ISSUE TITLE
老哥求救 上层版的问题 

### ISSUE THREAD

**Issue by Zyilin98** [liaozhelin/yds-charger#19]
在我烧了两个ESP32 + 两个SW3526 + N个加速度传感器 等等之后 终于写进去固件并且触发快充了
但是 上层版 这里两个led灯也不亮 拨码开关每次在写固件的时候才有效（也许无效但是确实是写进去了固件） 
很多功能还是没用办法用 请问一下老哥 这个拨码开关是如何鉴别能正常用的 我已经换了好几个了 还是不能用

**Comment by liaozhelin** [comment]
> 在我烧了两个ESP32 + 两个SW3526 + N个加速度传感器 等等之后 终于写进去固件并且触发快充了 但是 上层版 这里两个led灯也不亮 拨码开关每次在写固件的时候才有效（也许无效但是确实是写进去了固件） 很多功能还是没用办法用 请问一下老哥 这个拨码开关是如何鉴别能正常用的 我已经换了好几个了 还是不能用

呃呃，上层LED不亮下层亮应该就是焊接或者排针问题
