### ISSUE TITLE
配网连接WiFi的问题 一些小问题

### ISSUE THREAD

**Issue by Zyilin98** [liaozhelin/yds-charger#20]
昨天解决完硬件问题之后就开始配网 然后发现一个问题 就是配网之后 显示的ip 既不是我这里的公网ip 也不是内网ip 但是路由器网关哪里也确实是查到了这个设备在线
手动OTA固件就会卡住不动 没有反应。

![微信图片_20220622111621](https://user-images.githubusercontent.com/61766598/174936154-156cdcd1-cb31-425f-abe1-735b262980a3.jpg)
![微信图片_20220622111625](https://user-images.githubusercontent.com/61766598/174936157-1d4975cf-9f17-453b-8804-c98c8191eb77.jpg)

然后 topBoard这个pcb原来是单层板么 单层板就没法嫖嘉立创紫 😂

**Comment by Zyilin98** [comment]
去重刷了固件 还是一样的问题 获取的ip不对 手动没法ota(还是说这个功能没做) 我刷的是合并固件

**Comment by michael6555** [comment]
请问你的也是不是板子上预留给显示屏的位置不对？

**Comment by Zyilin98** [comment]
我这就感觉屏线短了点 把显示屏弯成直角感觉有点费劲 怕把屏搞坏



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月22日(周三) 中午12:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liaozhelin/yds-charger] 配网连接WiFi的问题 一些小问题 (Issue #20)




 
请问你的也是不是板子上预留给显示屏的位置不对？

**Comment by liaozhelin** [comment]
> 昨天解决完硬件问题之后就开始配网 然后发现一个问题 就是配网之后 显示的ip 既不是我这里的公网ip 也不是内网ip 但是路由器网关哪里也确实是查到了这个设备在线 手动OTA固件就会卡住不动 没有反应。
> 
> ![微信图片_20220622111621](https://user-images.githubusercontent.com/61766598/174936154-156cdcd1-cb31-425f-abe1-735b262980a3.jpg) ![微信图片_20220622111625](https://user-images.githubusercontent.com/61766598/174936157-1d4975cf-9f17-453b-8804-c98c8191eb77.jpg)
> 
> 然后 topBoard这个pcb原来是单层板么 单层板就没法嫖嘉立创紫 😂

1.这个IP我是用的乐鑫的方法直接读的，我后面验证下，你这个看起来像获取导公网IP了

**Comment by Zyilin98** [comment]
1.这个IP怎么看也不像是公网ip 这个ip查过去是美国AT&T 就很头秃 我感觉是哪里逻辑有问题
2.可能是表达问题吧 是铝外壳的前面板和后面板的pcb 这个好像就后面版是双层板 前面板好像是单层板
3.屏线这个我对的是屏线的两个洞对pcb上的洞 还是感觉屏线短了点 下次我自己焊接的时候看看能不能挪一挪
4.OTA服务器在Github么 也许我还得用网关级代理......   路由器之前为了别的智能设备关了双频合一  一会试试光猫自己的2.4Gwifi 再不行 我也就没办法了 看看新的固件版本会不会好一点
issue就不用开启了 能回复就行 谢谢老哥


对了，老哥有没有交流群之类的 这样就省的好多事开issue了

**Comment by liaozhelin** [comment]
> 1.这个IP怎么看也不像是公网ip 这个ip查过去是美国AT&T 就很头秃 我感觉是哪里逻辑有问题 2.可能是表达问题吧 是铝外壳的前面板和后面板的pcb 这个好像就后面版是双层板 前面板好像是单层板 3.屏线这个我对的是屏线的两个洞对pcb上的洞 还是感觉屏线短了点 下次我自己焊接的时候看看能不能挪一挪 4.OTA服务器在Github么 也许我还得用网关级代理...... 路由器之前为了别的智能设备关了双频合一 一会试试光猫自己的2.4Gwifi 再不行 我也就没办法了 看看新的固件版本会不会好一点 issue就不用开启了 能回复就行 谢谢老哥
> 
> 对了，老哥有没有交流群之类的 这样就省的好多事开issue了

1.呃，这个IP的问题我也不太清除，我这里看看能不能复现，因为我试了用wifi和手机热点获取到的都是本地ip，这个问题后面研究下
