### ISSUE TITLE
关于bom

### ISSUE THREAD

**Issue by gxq-is-a-lovely-girl** [liaozhelin/yds-charger#22]
在底板的bom中C1,C4,C44,C61,C65为一类，在元器件采购指南中C１,C44归为直插固态电容,而C65,C61,C4与C59,C60归为高频低阻直插铝电解电容,我应该按哪个?还有貌似C1,C44(220uf/35V)的尺寸大小bom中没有写是几成几,小白提问勿喷.

**Comment by Zyilin98** [comment]
这个东西 我怎么说 具体还得等作者回答 我自己的意见是 SW3526 和ip6525的示例电路中没标注非得是固态电容还是铝电解电容
我自己正好有点余料 刚开始做的是固态和电解混用 后来就是全换固态电容了 看那些做成的大佬 也是电解的多 
至于220uf的这个尺寸 我买的是8*11.5MM固态电容 之前库存的是8*12MM的电解电容

**Comment by Zyilin98** [comment]
> 这个选料具体还得等作者回答 
我自己的意见是 SW3526 和ip6525的示例电路中没标注非得是固态电容还是铝电解电容 我自己正好有点余料 刚开始做的是固态和电解混用 后来就是全换固态电容了 看那些做成的大佬 也是电解的多 至于220uf的这个尺寸 我买的是8_11.5MM固态电容 之前库存的是8_12MM的电解电容

**Comment by liaozhelin** [comment]
> 在底板的bom中C1,C4,C44,C61,C65为一类，在元器件采购指南中C１,C44归为直插固态电容,而C65,C61,C4与C59,C60归为高频低阻直插铝电解电容,我应该按哪个?还有貌似C1,C44(220uf/35V)的尺寸大小bom中没有写是几成几,小白提问勿喷.

我自己的话就只有C口输出的两个电容用了固态电容，其他都是普通铝电解电容，具体物料购买地址我记得我有附在采购指南中，您可以去看看
