### ISSUE TITLE
大佬，求指教，RY8411出来电压一直在3.7以上

### ISSUE THREAD

**Issue by xiyuxixi** [liaozhelin/yds-charger#23]
仅焊接原理图中的 输入模块和 3.3V降压模块。 5V输入测试RY8411输出3.7V多。12V的时候在3.5V多。20V输入又上升到3.8V输出。换了好几个RY8411都一样

**Comment by ktx888** [comment]
看你这描述不知道是怎么回事，不过我的可以稳定在3.3v

**Comment by Zyilin98** [comment]
建议拍个图片出来看看

**Comment by liaozhelin** [comment]
是的，这个电路很多人焊接后都没有问题，建议还是检查下器件是不是焊接有误
