### ISSUE TITLE
电感L1发热

### ISSUE THREAD

**Issue by gzzz2008** [liaozhelin/yds-charger#24]
电压不正常，而且电感L1 上电一会就发热了。

**Comment by gzzz2008** [comment]
还有能发一份能有电路连接的动态BOM图吗？这样好排查原因。

**Comment by gzzz2008** [comment]
还有为什么没有接地呢？

**Comment by liaozhelin** [comment]
> 还有能发一份能有电路连接的动态BOM图吗？这样好排查原因。

嘉立创的动态bom插件貌似有bug，我导出是空文件，所以之前用的是脚本导出，您邮箱发我个我给你发下源文件，您那里导出试试

**Comment by liaozhelin** [comment]
> 还有为什么没有接地呢？

CDEP电感第三个脚是固定而不是屏蔽，因此不用接低，电感发烫说明输出环路有问题，重点检查下芯片sw引脚和反馈引脚

**Comment by gzzz2008** [comment]
> > 还有能发一份能有电路连接的动态BOM图吗？这样好排查原因。
> 
> 嘉立创的动态bom插件貌似有bug，我导出是空文件，所以之前用的是脚本导出，您邮箱发我个我给你发下源文件，您那里导出试试

59029226@qq.com
