### ISSUE TITLE
显示屏接线相关优化

### ISSUE THREAD

**Issue by Zyilin98** [liaozhelin/yds-charger#26]
现在的pcb和显示屏之间是靠焊接 连接 而且现在屏线有长有短 经常有屏线够不到或者弯不过来的情况
就能不能改一下显示屏的接线方式
适配这种接线方式
![Screenshot_2022-06-26-12-51-43-405_com taobao taobao](https://user-images.githubusercontent.com/61766598/175799959-c6a44dad-2f17-4e1d-987b-9fadec4cf331.jpg)
我知道这种母座有点难焊
但是最起码可以减小焊接屏幕的损耗 将来屏幕坏了也方便更换

**Comment by ktx888** [comment]
1、借楼吐槽一下，我之前就买的这家的30pin的那款显示屏，边框大了一圈，根本装不进去，后来换了一家。
2、我觉得楼主提的也有道理。不过这个显示屏应该也不至于用着用着就坏了吧（我猜的）。
3、up主好像还没有发布新的固件，我自己改了代码，我的支持1分钟无操作自动息屏，也能保护屏幕。我还加了天气预报功能。如果有需要可以找我要，哈哈😃

**Comment by Zyilin98** [comment]
> 1、借楼吐槽一下，我之前就买的这家的30pin的那款显示屏，边框大了一圈，根本装不进去，后来换了一家。 2、我觉得楼主提的也有道理。不过这个显示屏应该也不至于用着用着就坏了吧（我猜的）。 3、up主好像还没有发布新的固件，我自己改了代码，我的支持1分钟无操作自动息屏，也能保护屏幕。我还加了天气预报功能。如果有需要可以找我要，哈哈😃

卧槽 我买的就是这家 卧槽了 能给一下你那个新一家的屏幕链接么

**Comment by ktx888** [comment]
【淘宝】https://m.tb.cn/h.fwWEmZ6?tk=Bq9x2or860c「0.96寸OLED显示屏 窄边框128*64点阵SSD1315驱动30PIN兼容SSD1306」
点击链接直接打开

**Comment by Zyilin98** [comment]
> 【淘宝】[https://m.tb.cn/h.fwWEmZ6?tk=Bq9x2or860c「0.96寸OLED显示屏](https://m.tb.cn/h.fwWEmZ6?tk=Bq9x2or860c%E3%80%8C0.96%E5%AF%B8OLED%E6%98%BE%E7%A4%BA%E5%B1%8F) 窄边框128*64点阵SSD1315驱动30PIN兼容SSD1306」 点击链接直接打开

感谢 这个屏线应该不会很短吧

**Comment by ktx888** [comment]
> 

不短，正好

**Comment by ktx888** [comment]
![QQ图片20220626141011](https://user-images.githubusercontent.com/78667688/175801973-11671a36-33c3-4136-8810-5b3f3fbb2e89.jpg)

**Comment by Zyilin98** [comment]
> 1、借楼吐槽一下，我之前就买的这家的30pin的那款显示屏，边框大了一圈，根本装不进去，后来换了一家。 2、我觉得楼主提的也有道理。不过这个显示屏应该也不至于用着用着就坏了吧（我猜的）。 3、up主好像还没有发布新的固件，我自己改了代码，我的支持1分钟无操作自动息屏，也能保护屏幕。我还加了天气预报功能。如果有需要可以找我要，哈哈😃

对了老哥 我顺带要一份固件吧 试试这个气象站 顺带也看一下我这是不是配网还有问题

**Comment by ktx888** [comment]
> > 1、借楼吐槽一下，我之前就买的这家的30pin的那款显示屏，边框大了一圈，根本装不进去，后来换了一家。 2、我觉得楼主提的也有道理。不过这个显示屏应该也不至于用着用着就坏了吧（我猜的）。 3、up主好像还没有发布新的固件，我自己改了代码，我的支持1分钟无操作自动息屏，也能保护屏幕。我还加了天气预报功能。如果有需要可以找我要，哈哈😃
> 
> 对了老哥 我顺带要一份固件吧 试试这个气象站 顺带也看一下我这是不是配网还有问题

你加我qq吧，烧程序可能有一些bug，好交流（1760489926）

**Comment by Runeluna** [comment]
> 【淘宝】[https://m.tb.cn/h.fwWEmZ6?tk=Bq9x2or860c「0.96寸OLED显示屏](https://m.tb.cn/h.fwWEmZ6?tk=Bq9x2or860c%E3%80%8C0.96%E5%AF%B8OLED%E6%98%BE%E7%A4%BA%E5%B1%8F) 窄边框128*64点阵SSD1315驱动30PIN兼容SSD1306」 点击链接直接打开

谢谢老哥，我搞的另一家也是大了一圈

**Comment by liaozhelin** [comment]
这个提议不错，有想自行修改的可以私发我下邮箱，我私发源文件。之前设计的时候我主要是用手头现有的屏幕，所以没有考虑这种接口的形式，果然做的人多考虑的事情就更加周全了👍

**Comment by Zyilin98** [comment]
> 这个提议不错，有想自行修改的可以私发我下邮箱，我私发源文件。之前设计的时候我主要是用手头现有的屏幕，所以没有考虑这种接口的形式，果然做的人多考虑的事情就更加周全了👍

我去试试看看能不能换种接口 但是主要是怕出现那种显示屏装不上的问题 我看看咋优化这个pcb板子的开口吧 我看周边应该没电路可能就是led那边的线可能要稍微挪挪 多切一点影响应该不大 我先试试

**Comment by blacksr** [comment]
！！我也买了这家！然后发现大了一圈，但是一直没管这个问题，将就用了，这就去换！

**Comment by blacksr** [comment]
！！我也买了这家！然后发现大了一圈，但是一直没管这个问题，将就用了，这就去换！
