### ISSUE TITLE
串口

### ISSUE THREAD

**Issue by chjdbh** [liaozhelin/yds-charger#27]
上电会出现串口一秒后消失再过一秒又会出现一直重复这样

**Comment by ktx888** [comment]
> 

拨盘往左拨之后再上电

**Comment by chjdbh** [comment]
还是不行

**Comment by ktx888** [comment]
按道理来说不应该，我之前也和你一样一直跳，但是我把排针中间那排最下面的引脚对地短接后（也就相当于拨盘向左拨），再上电就不跳了

**Comment by Dustl1ght** [comment]
> 上电会出现串口一秒后消失再过一秒又会出现一直重复这样

我之前也是这样，我换了个无源晶振就好了，之前用的有源晶振，不知道你是不是和我一样的问题

**Comment by Zyilin98** [comment]
我之前也有这个问题 加焊了一下usb线和接头 顺带对调了中间的数据线 也好了 不知道是不是这样的问题 
也许你得检查一下esp32的3.3V供电

**Comment by gzzz2008** [comment]
上电后，串口不显示，一点反应都没有，是怎么回事呢？是我操作顺序有问题？
