### ISSUE TITLE
芯片配网

### ISSUE THREAD

**Issue by Dustl1ght** [liaozhelin/yds-charger#28]
up大大你好，现在我遇到个问题是无法配网，2.4g频段也不行，我用的路由器是wifi6的，我看网上说esp32不支持最新的wifi协议，然后就是配网失败之后就不能再重新配网了，需要重新刷固件才可以

**Comment by ktx888** [comment]
兄弟我这有我修改过的固件，在up没更新前可以过渡，如果需要加我QQ发给你1760489926

**Comment by Dustl1ght** [comment]
> 兄弟我这有我修改过的固件，在up没更新前可以过渡，如果需要加我QQ发给你1760489926

多谢

**Comment by Zyilin98** [comment]
wifi6的路由器关掉多频合一 双频优选 等等 暴露出2.4GWiFi试试

**Comment by Dustl1ght** [comment]
> wifi6的路由器关掉多频合一 双频优选 等等 暴露出2.4GWiFi试试

好的好的，我试试
