### ISSUE TITLE
问一下，有可能公开esp固件的代码么

### ISSUE THREAD

**Issue by yelvlab** [liaozhelin/yds-charger#3]
为了学习思路，实话您这个项目看成品做的效果不错，但是开源之名多多少少差点意思，搭配硬创社，没话说，有可能的话留个话，没可能就关了吧

**Comment by liaozhelin** [comment]
说了开源那肯定得开，正在修改依赖的子模块，预计晚上可以上线第一个版本。至于硬创社和我这个项目关系不大，因为这里的资料比硬创社更全

**Comment by liaozhelin** [comment]
ho

> 为了学习思路，实话您这个项目看成品做的效果不错，但是开源之名多多少少差点意思，搭配硬创社，没话说，有可能的话留个话，没可能就关了吧

说了开源，那肯定要开的，我还希望有大佬能帮我提交PR完善后续固件，审查我的代码呢。已经整理的差不多了，预计晚上可以上传第一个版本，工作区有点乱正在整理中。至于硬创社，并没有资料是在硬创社独有的，只是给没办法访问github的朋友们一个更方便下载资料的地方（最近gitee都知道，提交每次审核那得烦死），最后希望开源后能够有大佬们一起完善这个项目，我主要用业余时间搞的，很多细节可能都不是很到位，只要不被商业化拿来盈利就可以了😼😼

**Comment by liaozhelin** [comment]
已提交源码工程
