### ISSUE TITLE
[硬件] BOM的型号和实际好像有出入

### ISSUE THREAD

**Issue by Runeluna** [liaozhelin/yds-charger#31]
买元件的过程中发现BOM的型号和实际好像有出入，比如C4在bom标注的是220uF，看购买说明上好像是100uF，这个有影响吗，以哪个为准？
还有我看到有一个保险丝座，请问下保险丝选哪种规格，多少V和A的，谢谢

**Comment by Dustl1ght** [comment]
> 买元件的过程中发现BOM的型号和实际好像有出入，比如C4在bom标注的是220uF，看购买说明上好像是100uF，这个有影响吗，以哪个为准？ 还有我看到有一个保险丝座，请问下保险丝选哪种规格，多少V和A的，谢谢

我全部按照bom买的，目前没有出现问题，保险丝座嘉立创搜索0154007.DR，总之保险丝座就长这样。保险的规格我一开始用的125V 3A 上电就烧，我后来直接上了125V 10A。这个0154007.DR是7A的，我觉得应该也没问题。

**Comment by liaozhelin** [comment]
是的，大部分应该是对的上的，其实也没有多少料，主要是用LCEDA直接生成，应该按照料号都可以找到
