### ISSUE TITLE
有人可以给个全套bom的购买链接吗我买不到

### ISSUE THREAD

**Issue by 2905058350** [liaozhelin/yds-charger#36]
有人可以给个全套bom的购买链接吗我买不到

**Comment by XiDD93** [comment]
淘宝自己慢慢加入购物车或者直接在立创商场上传bom

**Comment by 2905058350** [comment]
> 淘宝自己慢慢加入购物车或直接在立创商场上传bom

可以加你还有发一下吗？就小的贴片的买不到大的可以

**Comment by galamygod** [comment]
> 

看封装，直接搜封装就可以了
