### ISSUE TITLE
烧LMBT3904DW1T1G

### ISSUE THREAD

**Issue by XiDD93** [liaozhelin/yds-charger#37]
之前接12v电源没问题，测试完了上19v电源直接LMBT3904DW1T1G着火烧了，换了新的以后接12v电源也一样烧，找了一圈发现SI2309被卖家发错货发成SI2301了，烧LMBT3904DW1T1G会是SI2301的问题吗？

**Comment by Zyilin98** [comment]
会

**Comment by liaozhelin** [comment]
我的锅，这里上拉电阻应该要改成10K，不过你这着火应该是买错器件了，用1K也就是发热量大

**Comment by e1585742133** [comment]
建议拆掉就行了
