### ISSUE TITLE
两个C口均只能输出最高12V

### ISSUE THREAD

**Issue by Dustl1ght** [liaozhelin/yds-charger#38]
我插入我的笔记本电脑只能只能输出12V，无法输出20V，而且需要上电几次才能稳定12V，重新拔插C口数据线有概率会重启设备，我之前已经成功组装了两个了，装第三个的时候出现这个问题了 [https://www.bilibili.com/video/BV1t34y1p72V?share_source=copy_web](url)
@liaozhelin

**Comment by stig3** [comment]
你看一下你的输入电源是多少伏的，这个是BUCK型的电源。
另外，看你的描述，感觉是协议没有识别，检查一下焊接呢？

**Comment by Dustl1ght** [comment]
> 你看一下你的输入电源是多少伏的，这个是BUCK型的电源。 另外，看你的描述，感觉是协议没有识别，检查一下焊接呢？

 谢谢，电源是24V 6A的，我之前已经焊过两个板子了，都用的挺好，这是第三个，然后就出问题了，而且两个C口都是同样的问题，两个C口的电路都是分开的，按说也不至于两个都这样，会不会是我拿错电容或电阻了

**Comment by liaozhelin** [comment]
重点检查焊接以及器件焊接问题
