### ISSUE TITLE
后期是否可以考虑采用彩色TFT屏幕

### ISSUE THREAD

**Issue by stig3** [liaozhelin/yds-charger#4]
0.96寸的彩色LCD屏幕
价格11左右
SPI驱动，也不存在烧屏的风险
另外显示效果要好很多，参照
![image](https://user-images.githubusercontent.com/3666343/172078871-fa74e571-0ab8-4c3c-a712-caecd4ce429c.png)

**Comment by liaozhelin** [comment]
是的，彩屏会好很多，主要是排线不是很好处理，目前看中0.96款的，可能还得设计转接板，下一代会考虑的
