### ISSUE TITLE
SW3526发热

### ISSUE THREAD

**Issue by gzzz2008** [liaozhelin/yds-charger#40]
SW3526总是发热是怎么回事呢？哪里能短路导致呢？

**Comment by gzzz2008** [comment]
好像是IP6525T发热！！我用的是IP6505，这个有影响吗？

**Comment by gzzz2008** [comment]
换了IP6525T正常了，但是怎么插电脑没有反应呢？？需要按上上层板子才能插电脑有反应吗？

**Comment by Zyilin98** [comment]
不接上层板子 esp32应该是不进bootload模式 电脑应该不认

**Comment by galamygod** [comment]
> 好像是IP6525T发热！！我用的是IP6505，这个有影响吗？

不能直接使用6505，他俩脚位不一样的
