### ISSUE TITLE
如何下载程序

### ISSUE THREAD

**Issue by gzzz2008** [liaozhelin/yds-charger#41]
测试电压都是正常的，怎么能下载程序呢？连接电脑一点反应都没有，是不是哪里操作不对呢？能给详细点的教程吗？

**Comment by ktx888** [comment]
3.3v供电正常吗

**Comment by gzzz2008** [comment]
都是3.2v多，应该算是正常吧。

**Comment by galamygod** [comment]
> 都是3.2v多，应该算是正常吧。

我也卡在这步，up说下载驱动，但是我在官网硬是没找到

**Comment by xiaoqingnian20** [comment]
先确认芯片是c3fn4的，4行丝印的那种芯片，3行丝印的不带内存，用给的esp32下载工具通过接D+ D- 3.3vvcc gnd  gnd短接gpio9  上电 识别到端口点下载即可

**Comment by liaozhelin** [comment]
README中有详解
