### ISSUE TITLE
谁有多余配套的元件，淘宝和嘉立创上买太贵了，收购3套。

### ISSUE THREAD

**Issue by thbaobao** [liaozhelin/yds-charger#42]

**Comment by fggddfor** [comment]
我这电容+电感有剩，打包便宜卖你，邮件fggddforchina@gmail.com

**Comment by liaozhelin** [comment]
器件还是自己找吧，淘宝不贵

**Comment by 2905058350** [comment]
> 我这+电感有剩，打包卖掉你，邮件[fggddforchina@gmail.com](mailto:fggddforchina@gmail.com)

发邮件给你了
