### ISSUE TITLE
有人可以给一个BOM的购买链接吗？我买不到 或者直接卖我两套

### ISSUE THREAD

**Issue by 2905058350** [liaozhelin/yds-charger#44]

**Comment by liaozhelin** [comment]
自己动手丰衣足食呀，没多少器件

**Comment by 2905058350** [comment]
> 自己动手丰衣足食呀，没多少器件

![image](https://user-images.githubusercontent.com/70979075/178104321-bfec8a40-e7d8-4e12-8473-89134cee595a.png)
这些我找不到
