### ISSUE TITLE
插上电源屏幕和灯不亮

### ISSUE THREAD

**Issue by gzzz2008** [liaozhelin/yds-charger#45]
用下载口接3.3V的电源可以找到串口下载程序，但是接DC电源不行，但是测量出来的电压都是3.27V，应该差不多吧。但是下载程序后，接上电源屏幕不亮，A口和C口都有电压输出，但是屏幕不亮，灯也不亮，USB接下载口，也没反应，找不到串口。

**Comment by gzzz2008** [comment]
ESP32 可以下载进去程序，

**Comment by liaozhelin** [comment]
可以下载进去程序屏幕不亮多半是屏幕焊接的问题
