### ISSUE TITLE
烧写程序时电压不正常

### ISSUE THREAD

**Issue by fggddfor** [liaozhelin/yds-charger#48]
从ESP32C3出来的USB D+ 3.3v、USB D- 1v
现在插上电脑，电脑就死机了……

**Comment by Zyilin98** [comment]
你看看你是不是焊接有问题 别到时候充电器没做好 把电脑带走了

**Comment by fggddfor** [comment]
感谢大佬，是我没接gnd导致的，之前只接了D+ D-，现在再接一根GND电脑就可以识别了

**Comment by fggddfor** [comment]
接上GND后电脑不死机了，设备管理器也读出是个usb/jtag设备，但出现一秒就消失，然后一直循环，Windows的自动驱动安装也失败

**Comment by Zyilin98** [comment]
应该是不需要驱动也可以  看看是不是3.3V不到位 还是接触问题

**Comment by fggddfor** [comment]
![Uploading 7599C77E-91D8-4AEA-8359-905B862CBA10.jpeg…]()
3.3是到位的，现在就是没有驱动

**Comment by liaozhelin** [comment]
不断闪现循环是没有进入下载模式的问题，这个在其他issue中也有提及

**Comment by fggddfor** [comment]
大佬给个驱动，现在识别到有两个USB JTAG/serial debug unit，但找不到驱动，用项目中的drivers也只能个一个USB JTAG/serial debug unit打上驱动
也看不到串口号

**Comment by Zyilin98** [comment]
我都没打驱动你敢信😂 我win11插上就认了 com4



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月9日(周六) 下午5:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liaozhelin/yds-charger] 烧写程序时电压不正常 (Issue #48)




 
大佬给个驱动，现在识别到有两个USB JTAG/serial debug unit，但找不到驱动，用项目中的drivers也只能个一个USB JTAG/serial debug unit打上驱动
 也看不到串口号

**Comment by fggddfor** [comment]
感谢大佬，我把win7升到了win10就可以正常识别了
