### ISSUE TITLE
按键无反应 c1 c2无输出

### ISSUE THREAD

**Issue by xiaoqingnian20** [liaozhelin/yds-charger#49]
![IMG_20220709_113145](https://user-images.githubusercontent.com/89372710/178095728-1e482732-87cc-445d-a565-f5de8c1cedf3.jpg)
![IMG_20220709_143939](https://user-images.githubusercontent.com/89372710/178095736-a6081b8b-c032-4e9f-9d03-73d2d03676ea.jpg)
接20v输入 不接时就有0.4v左右电压
接c口显示最高只有3w输出但也还是不充电
无法解决

**Comment by xiaoqingnian20** [comment]
启动后按键也无反应，但启动前可以左拨进烧写模式

**Comment by liaozhelin** [comment]
重点检查C口的焊接 ，尤其是CC线，空载0.几V是正常现象，电压触发后默认最低是5V，你试着用个OTG头看看能否触发5V
