### ISSUE TITLE
器件选型问题

### ISSUE THREAD

**Issue by stig3** [liaozhelin/yds-charger#5]
1. R5/R12 两个电阻，规格书要求接33K 1%的实现 65W MAX 输出，原理图上是34K，这个有什么考虑吗？34K是非标电阻，也买不到。
2. R17/R18是开关电源的FB，31K也是非标电阻，建议使用62K/20K这样的搭配
3. C42/C25这两个22uF的电容是跨接在USB BUS上的，这两个电容耐压有要求，不能小于20V，建议标注出来，不然会炸的。
4. C62/C34这两个10uF的电容也要16V电压档的
5. C58这个0603的电容也要耐压35V的

**Comment by liaozhelin** [comment]
1. R15/R12这两个电阻，可以使用33K的，这个实际上应该不焊接都可以，作用是在没有I2C配置sw3526时候，通过电阻配置功率

**Comment by liaozhelin** [comment]
已经更新文件
