### ISSUE TITLE
来交作业了

### ISSUE THREAD

**Issue by fggddfor** [liaozhelin/yds-charger#50]
另外，在测试过程中发现18wA口的输出电路发热量普遍较大，输出18w时上散热垫不到10分钟外壳都烫手，特别是IP6525T和LMBT3904DW1T1G
![5F37CE12-B9D6-47D2-B2EA-7CEE66EAEC00](https://user-images.githubusercontent.com/107621523/178149803-5aef9b9a-1baf-4bab-964a-baff32842b78.jpeg)
![0859B5E5-9DD9-47F2-B4ED-5D448F070014](https://user-images.githubusercontent.com/107621523/178149805-945a139d-5c3b-4103-b640-1bf928b1905d.jpeg)
l![C7FBECCE-C69E-46E7-917F-6B04215AB2C0](https://user-images.githubusercontent.com/107621523/178149793-7e316746-e96c-4833-9179-50757f63ba08.jpeg)
![8924C3CC-A07F-4E92-B6C8-AC44B4AF0D31](https://user-images.githubusercontent.com/107621523/178149797-cb8e79a6-6e92-47ef-bad6-7af485081ad3.jpeg)
![6C5D4BC0-8CCB-471E-8002-18DD585FFA46](https://user-images.githubusercontent.com/107621523/178149800-76c50faf-687c-4726-beeb-7a6eac58f8c2.jpeg)

**Comment by mornlena** [comment]
你焊接是否有问题啊，我的目前最多测试2个a口18瓦，2个c口20瓦，同时，时间30分钟，外壳温度也就40左右，加了散热垫的。

**Comment by fggddfor** [comment]
大佬能拍一张下层板的照片吗？我对照着看看

**Comment by mornlena** [comment]
拍照片看不出来的，需要你仔细的检查，用维修电源看看输入功率和输出功率对比。你做几套啊，都这样吗？我这里一共做了3套，除了无线信号不太好和那个3d传感器总是无法工作以外，其他都没问题。

**Comment by fggddfor** [comment]
做了五套，无线wifi总是收不到信号，转换效率都在67%左右，就很懵

**Comment by liaozhelin** [comment]
3904发热问题可以查看其他issue，刚刚也推送了修正后的文件，修改两个上拉电阻即可

**Comment by mornlena** [comment]
> 做了五套，无线wifi总是收不到信号，转换效率都在67%左右，就很懵

wifi没信号，你首先把这个放到无线路由器旁边看能不能收到信号，如果还是没有的话，检查晶振和晶振旁边的两颗电容，我的之前是有一个空焊了。67的效率太低了，发热肯定大，检查一下具体是哪里的原因吧。

**Comment by vicen26** [comment]
我这边做了3套，都是无法配网，一配网就自动重启，或者没收到，有大佬知道原因吗

**Comment by vicen26** [comment]
顺便问下大佬用得是哪个固件

**Comment by fggddfor** [comment]
把拨盘向左拨再上电
ESP32只支持2.4G的wifi
固件我用的lssues中open的那个大佬的固件

**Comment by vicen26** [comment]
> 

我用的是2.4G 的，智能插座那些都能配网，我两个固件都刷过，原版的固件配了几次网没配上，现在进入配网就会自动重启，另一个固件死活配不上
