### ISSUE TITLE
[交流]显示屏保护问题

### ISSUE THREAD

**Issue by Zyilin98** [liaozhelin/yds-charger#52]
我现在加了外壳之后发现 显示屏上端正好跟铝制外壳精准贴合 没啥缝隙 如果摔一下或者磕一下就很有可能把显示屏磕碎
我有想过挪一下显示屏的位置和连接方式 但是板子上空间有限没法转移 
就想问问各位大佬们 能不能集思广益 解决一下显示屏的保护问题 至少不会说摔一下 不仅显示屏寄了 主板也可能寄

**Comment by mornlena** [comment]
我的是可以正好卡在里面的，你应该可以调整一下，或者你买的屏幕比我们的大一圈，换一种屏幕吧。

**Comment by Zyilin98** [comment]
> 我的是可以正好卡在里面的，你应该可以调整一下，或者你买的屏幕比我们的大一圈，换一种屏幕吧。
不是说屏幕压着铝壳 是刚好铝壳和屏幕之间没啥缝隙 精准卡进去

**Comment by liaozhelin** [comment]
可以用薄的电工胶布保护下，缝隙的话应该还是有一点排线的空间，但是不多

**Comment by Zyilin98** [comment]
> 可以用薄的电工胶布保护下，缝隙的话应该还是有一点排线的空间，但是不多

我试试 昨天晚上本来没想到这个问题 手滑摔了才想起来这个问题 然后给屏幕包了点透明胶 但是还是没什么效果 我试试电工胶带吧
