### ISSUE TITLE
未识别的USB设备 && 晶振方向问题

### ISSUE THREAD

**Issue by TheRealKamisama** [liaozhelin/yds-charger#53]
在刷写固件的过程中接上电脑发现弹窗: 未识别的USB设备  
翻阅issue得知可能跟晶振方向有关, 我这里晶振方向见照片  
![QQ图片20220711225132](https://user-images.githubusercontent.com/35005476/178292808-d9de6e58-4ecd-4eb6-9db5-41412eedc8c5.jpg)  
(图中Q4错位了, 下次上热台返工)
按照 #21 提出的方法我测了一下, 目前晶振的左上和右下是导通的, 我想请教一下这个方向正确吗?  
如果晶振方向正确, 目前还有什么排查的思路?

**Comment by mornlena** [comment]
晶振靠近芯片和天线的那个脚是1脚，天线也反了啊啊。

**Comment by QQ5547155** [comment]
个人也出现插U口电脑不识别的情况，而且是反复弹窗，开始以为是晶振的问题，我买的晶振比较小，但检查没有问题，仔细看大佬的文字内容和图纸，后来发现一个是需要插电之前把编码开关转至PCB板日期的方向，但还是不行，再检查发现USB线序错误，把U+和U-换个方向，再把编码开关拨一边上电，就都正常了。如有出现类似问题的，仅做参考！感谢大佬开源！！

**Comment by fggddfor** [comment]
天线没有方向吧，我也是点在左边，有信号连上后强度不弱但有些时候就连不上

**Comment by mornlena** [comment]
红点是1脚，1脚靠近芯片，电路图是这么画的。否则没必要特别标注啊，就好比mlcc电容或者电阻，从来不标正负极

**Comment by xiaoqingnian20** [comment]
晶振不需要关心方向，换D+ D- 左拨进刷机模式即可
