### ISSUE TITLE
上电c2显示的电压0-5v乱跳,且无法进入系统设置

### ISSUE THREAD

**Issue by XADZ139** [liaozhelin/yds-charger#57]
大佬你好
上电c2显示的电压0-5v乱跳,左下方有个充电标志在闪，而且按开关进入不了系统设置，求解
![image](https://user-images.githubusercontent.com/109009890/179342545-5ccf7ae6-d183-40ac-b7d7-43a2b7e3449a.png)

程序是这个
![image](https://user-images.githubusercontent.com/109009890/179342552-13d3d916-d318-47f5-9735-6c4fecc54530.png)

**Comment by galamygod** [comment]
可以试试风枪加焊U1，我的有一个也这样，加焊以后好了，或者你看看C口是不是连锡了

**Comment by xiyuxixi** [comment]
C 口没有设备的情况下默认是0V或者0.0几V。你都显示5V了，检查CC线路C口和芯片是否焊接正常。
