### ISSUE TITLE
为什么卡固件更新啊

### ISSUE THREAD

**Issue by 524322406** [liaozhelin/yds-charger#60]
如题。请耐心等待。。。连上路由器后跟路由器的ip不是一样的，例如路由器上显示该ip是192.168.0.103，充电器上显示的ip是56.54.51.50

**Comment by 524322406** [comment]
> 终于看到跟我一样的了，ip显示不对，我的只有最后一位是正确的。

我刷了楼下大佬的固件，正常了，并且成功更新

**Comment by blacksr** [comment]
问题如果处理好了的话请麻烦关闭一下Issues噢
