### ISSUE TITLE
无线充电

### ISSUE THREAD

**Issue by sinary-sys** [liaozhelin/yds-charger#62]
有加入无线充电的想法吗，毕竟目前的手机，基本都支持无线充电

**Comment by galamygod** [comment]
> 有加入无线充电的想法吗，毕竟目前的手机，基本都支持无线充电

我直接在上层塞了一块20w的小板，固定好以后再贴电胶布，然后上壳挖两个孔把线圈的引脚放进去，无线充电的小板直接飞线接到dc供电座，代价就是有点丑而且电源只能用12V的，不过放办公室用也是完全够了
