### ISSUE TITLE
RY8411 输出4.3V几的电压，问下大概是哪里的问题？

### ISSUE THREAD

**Issue by Krnus** [liaozhelin/yds-charger#63]
RY8411 测出来的都是4.37v的电压🤨

**Comment by galamygod** [comment]
四条线，红色供电不接就行了呗，DC插头插上，电脑检测到端口就可以烧录了

**Comment by Krnus** [comment]
> 四条线，红色电源不接就行了呗，DC插头插上，电脑检测到端口就可以烧录了

GND D+ D-  直接插电脑检测不到

**Comment by galamygod** [comment]
> > 四条线，红色电源不接就行了呗，DC插头插上，电脑检测到端口就可以烧录了
> 
> GND D+ D- 直接插电脑检测不到

DC供电啦，万用表打一下3.3V有没有出

**Comment by SuperPrintf** [comment]
你找一个USB-A公口，然后把线引出来就行了，GND、D+、D-，VCC连接一个LDO再出来就好

**Comment by xiaoxinabc** [comment]
我也不能识别 接了DC.  3.3v也有了 用的usb线连接的三个下载GND、D+、D-  识别不到 
是不是没有取东西啊 
弄了好久了

**Comment by SuperPrintf** [comment]
> 我也不能识别 接了DC. 3.3v也有了 用的usb线连接的三个下载GND、D+、D- 识别不到
> 是不是没有驱动呀
> 弄了好久了

你是不是没共地？

**Comment by galamygod** [comment]
> 
不仅仅是烧录脚的3.3，还要看e主控有没有电压，你测一下c15是不是3v左右

**Comment by galamygod** [comment]
> 我也不能识别接了 DC。3.3v也有用的usb线连接的三个下载GND、D+、D- 不知 是不是没有驱动呀 弄了好久了

你看一下c15有没有电压，看看主控有没有通电

**Comment by galamygod** [comment]
> 我也不能识别接了 DC。3.3v也有用的usb线连接的三个下载GND、D+、D- 不知 是不是没有驱动呀 弄了好久了

电脑是win10的话都不用安装驱动的

**Comment by xiaoxinabc** [comment]
是win10可能还是硬件没弄好

**Comment by xiaoxinabc** [comment]
刚刚量了 c15 有电压，但是从3v一直在往下降

**Comment by galamygod** [comment]
> 刚刚量了 c15 有电压，但是从3v一直在往下降

加焊一下主控试试，或者换一片

**Comment by xiaoxinabc** [comment]
今天下班 重新焊接 现在还是不行 崩溃

**Comment by blacksr** [comment]
> 今天下班 重新焊接 现在还是不行 蓝瘦啊

识别不到的话大概率是32芯片没有焊接好，你是用什么焊接的呢，QFN封装风枪还是挺容易虚焊的，建议用烙铁加焊一遍
识别不到可以按照下面步骤排查一下问题
1、如果使用的是DC供电在连接电脑前测量烧录口四个脚的正负有没有3.3V
2、如果3.3没问题的话插上电脑设备管理器是否有反应（新设备接入）
3、没有反应的话大概率是32芯片虚焊
4、有反应的话恭喜你烧录口到32芯片的硬件焊接是没有问题的，这时候需要将上板接上开关往左拨再上电进入bootmode
5、如果设备是识别到然后又不见了，类似一直插拔的效果的话同样开关左拨进入bootmode就正常了
6、查看电脑是否识别出一个串口或未知设备，有串口就不需要安装驱动，有新的未知设备接入就需要将这个未知设备装上驱动，驱动文件在仓库里面的，驱动正常后会有一个串口号，然后就可以进行烧录的动作了
