### ISSUE TITLE
大佬你好，请问能否出一个顶层无电容钻孔的版本？

### ISSUE THREAD

**Issue by SuperPrintf** [liaozhelin/yds-charger#64]
我在尝试全部使用固态电容，全部使用了 8*8规格的电容，它们的高度刚好在层间可容纳的范围之内，所以我在考虑能否将顶部板的电容孔去掉。但是拿到的是Gerber制板文件没办法进行修改，想请问一下大佬能否再出一款没有电容钻孔的版本。
这是我的成品图
[图1].https://tva1.sinaimg.cn/large/e6c9d24ely1h4eom4c5hcj21400u0n3b.jpg
[图2].https://tva1.sinaimg.cn/large/e6c9d24ely1h4eokp7fq3j21400u0n3n.jpg
可以看到电容的高度是可以控制在上层板之下的（上层板的位置刚好在两颗CDRH127NP的最高处），所以上下层之间的空间是完全可以容纳下电容的

**Comment by galamygod** [comment]
我靠，8*8在哪买的，能给个链接吗

**Comment by SuperPrintf** [comment]
> 我靠，8*8在哪买的，能给个链接吗

35V100uF:https://m.tb.cn/h.fxuesfN?tk=pj2M2JICx1R CZ3457
16V470uF:https://m.tb.cn/h.fyHj4dF?tk=eoGj2JIyKuQ CZ0001
35V220uF:https://m.tb.cn/h.fDDYrzx?tk=EFLq2JIym8C CZ3457

**Comment by liaozhelin** [comment]
可以发邮箱给我，我发你源文件
