### ISSUE TITLE
[Warn]某些设备不支持快充可能需要关闭PPS

### ISSUE THREAD

**Issue by Zyilin98** [liaozhelin/yds-charger#65]
最近从多个渠道观察到 某些设备在使用一些别的充电器的时候 能正常的进行快充 而到了智融芯片的设备就不能正常快充 症状是只能握手最低5V电压 然后求证过后发现是 PD PPS协议作祟
所以 还请各路大佬能在固件里加个 PD PPS 协议的开关(SW3526的i2s总线应该是能关闭这个的) 防止这些稀有设备 快充问题

#33  这位大佬的固件已经支持关闭PPS快充 如果有小米手机用户充电仅触发5V 可以去试试这位大佬的固件

**Comment by stig3** [comment]
SW3526的i2s总线应该是能关闭这个的
------------------------------------------
你这个消息从那里看到的？
我看了规格书还有iic协议，没有关闭这个协议的
iic只能设置功率读取芯片状态。

**Comment by Zyilin98** [comment]
> ## SW3526的i2s总线应该是能关闭这个的
> 你这个消息从那里看到的？ 我看了规格书还有iic协议，没有关闭这个协议的 iic只能设置功率读取芯片状态。
https://item.taobao.com/item.htm?spm=a230r.1.14.27.1f9a4f23cJaIgt&id=671728778645&ns=1&abbucket=4#detail
你看这个 同样也是sw3526 在他的固件里就设置了pps协议等等等协议的软件开关 同时他连pcb都发出来了
https://item.taobao.com/item.htm?spm=a1z10.5-c.w4002-5539902433.19.6c1d51dbWXiiB7&id=624481901312
这个是SW3518S 这个我还特意去问了 是通过i2s总线关闭sw3518S的pps快充的

**Comment by stig3** [comment]
我看了协议，的确是可以的

操作寄存器A9就可以
![image](https://user-images.githubusercontent.com/3666343/181204376-c8e10625-fb5a-41b5-ac2e-c242f14580eb.png)

你可以尝试在
```c
SW35xxWriteReg(SW35XX_PWR_CONF,0x07,SW_I2C_2);//设定功率限制为64W
```
之前增加
```c
SW35xxWriteReg(0xA9,0x3F,SW_I2C_2);//操作0xA9寄存器 关闭前两位PPS设置
SW35xxWriteReg(SW35XX_PWR_CONF,0x07,SW_I2C_2);//设定功率限制为64W
```

你可以试一下，我没有相关设备，没法测试。

**Comment by Zyilin98** [comment]
> 我看了协议，的确是可以的
> 
> 操作寄存器A9就可以 ![image](https://user-images.githubusercontent.com/3666343/181204376-c8e10625-fb5a-41b5-ac2e-c242f14580eb.png)
> 
> 你可以尝试在
> 
> ```c
> SW35xxWriteReg(SW35XX_PWR_CONF,0x07,SW_I2C_2);//设定功率限制为64W
> ```
> 
> 之前增加
> 
> ```c
> SW35xxWriteReg(0xA9,0xC0,SW_I2C_2);//操作0xA9寄存器 关闭前两位PPS设置
> SW35xxWriteReg(SW35XX_PWR_CONF,0x07,SW_I2C_2);//设定功率限制为64W
> ```
> 
> 你可以试一下，我没有相关设备，没法测试。

刚看见 感谢老哥的代码分享 顺便问一句 这个不会影响20v pd档位的诱骗吧
我有时间修改源码 编译一版试试
