### ISSUE TITLE
请问大佬输入延时+防反接+过流保护模块中的R19阻值和OLED显示模块中的R9阻值分别是多少呢，还有C63和C53的容值分别是多少呢

### ISSUE THREAD

**Issue by linkinparkone** [liaozhelin/yds-charger#67]
这个模块中的R9阻值是多少呢？
![image](https://user-images.githubusercontent.com/57856208/180960646-2557f00c-01df-4a1e-8efd-9b01de269b3d.png)

OLED显示模块中的R9阻值是4.7k吗
![image](https://user-images.githubusercontent.com/57856208/180960377-f5c7e476-a405-4adc-a384-867d773daa9e.png)

**Comment by linkinparkone** [comment]
C53的容值是多少呢？
![image](https://user-images.githubusercontent.com/57856208/180963158-4aede772-905f-41ba-a1cb-ebf5af7a4a46.png)

C63的容值是多少呢

**Comment by 1075081239** [comment]
我推测R9就是4.7k

**Comment by linkinparkone** [comment]
> 

![image](https://user-images.githubusercontent.com/57856208/181000189-0d360951-7876-4455-98f0-78fad959ad59.png)
我在csdn上找到了这个显示屏驱动电路，确实4.7k

**Comment by 1075081239** [comment]
> C53的容值是多少呢？ ![image](https://user-images.githubusercontent.com/57856208/180963158-4aede772-905f-41ba-a1cb-ebf5af7a4a46.png)
> 
> C63的容值是多少呢

![image](https://user-images.githubusercontent.com/33981454/181019005-46926400-2f7d-48c5-9e71-f87866aa7f0c.png)
我查阅了RY8411的芯片手册，这个电容应该是Cff
![image](https://user-images.githubusercontent.com/33981454/181019226-1402163f-697c-4716-a69a-785adee971df.png)
由于芯片有内部电路补偿，这个电容可以不加，如果加可以按以上公式计算。

**Comment by linkinparkone** [comment]
非常感谢您的回复，不过我不懂这个Fcross（cross frequency）是什么意思。在此图中应该取什么值呢



------------------&nbsp;Original message&nbsp;------------------
From: "destineda"; 
Sendtime: Tuesday, Jul 26, 2022 9:37 PM
To: "liaozhelin/yds-charger"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [liaozhelin/yds-charger] 请问大佬输入延时+防反接+过流保护模块中的R19阻值和OLED显示模块中的R9阻值分别是多少呢，还有C63和C53的容值分别是多少呢 (Issue #67)





  
C53的容值是多少呢？ 
 
C63的容值是多少呢
  

 我查阅了RY8411的芯片手册，这个电容应该是Cff
 
 由于芯片有内部电路补偿，这个电容可以不加，如果加可以按以上公式计算。

**Comment by 1075081239** [comment]
emmm这个需要作者分析网络了，我也不知道（无奈doge）

**Comment by 1075081239** [comment]
问了一下群友，NC应该都不用接

**Comment by Krnus** [comment]
> 问群友，NC应该用接

方便拉一下群吗

**Comment by blacksr** [comment]
其实那些NC、NA不接都是可以用的，当然我不太清楚你是不是要做什么其他功能

**Comment by linkinparkone** [comment]
不做别的功能，只是想复刻这个项目。不接那就省事儿了，谢谢啦



发自我的iPhone


------------------ 原始邮件 ------------------
From: blacksr ***@***.***&gt;
发送时间: 07/31/2022, 02:56
To: liaozhelin/yds-charger ***@***.***&gt;
抄送: lrvin ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [liaozhelin/yds-charger] 请问大佬输入延时+防反接+过流保护模块中的R19阻值和OLED显示模块中的R9阻值分别是多少呢，还有C63和C53的容值分别是多少呢 (Issue #67)





 
其实那些NC、NA不接都是可以用的，当然我不太清楚你是不是要做什么其他功能
