### ISSUE TITLE
如果使用jlink cmsis-dap 应该怎么接线 我手里暂时还没有usb公头

### ISSUE THREAD

**Issue by Zyilin98** [liaozhelin/yds-charger#7]
老哥 如果使用jlink cmsis-dap 应该怎么接线 我手里暂时还没有usb公头 再为了这个去买 感觉有点不值

**Comment by liaozhelin** [comment]
> 老哥 如果使用jlink cmsis-dap 应该怎么接线 我手里暂时还没有usb公头 再为了这个去买 感觉有点不值

这个硬件上无法使用JLINK下载，JLINK的JTAG占用管脚过多，C3引脚都用完了没有引出，USB公头就几分钱一个，所以选用的片内USB下载，这个USB也内建了JTAG调试器的

**Comment by Zyilin98** [comment]
串口下载有办法么 没有的话我还是去拆条usb线吧

**Comment by liaozhelin** [comment]
> 串口下载有办法么 没有的话我还是去拆条usb线吧
可以串口下载，但是我没有验证，板子背面预留了串口触点，应该是一样的，就是可能需要手动进入boot模式
