### ISSUE TITLE
问下电压电流异常充电站会这么显示，发出什么样的报警？

### ISSUE THREAD

**Issue by Inevitableofcold** [liaozhelin/yds-charger#70]

**Comment by Inevitableofcold** [comment]
问下电压电流异常充电站会怎么显示，发出什么样的报警？

**Comment by ktx888** [comment]
设置->系统监控->异常代码

**Comment by ktx888** [comment]
uint8_t event = u8x8_GetMenuEvent(u8g2_GetU8x8(&u8g2));
    u8g2_ClearBuffer(&u8g2);
    u8g2_DrawUTF8(&u8g2, 0, 15, "C1异常代码");
    u8g2_DrawUTF8(&u8g2, 20, 31, "系统无故障");
    if (sw35xx_c1.state.val_input_upmax)
      u8g2_DrawUTF8(&u8g2, 20, 31, "输入电压过高！");
    if (sw35xx_c1.state.tem_alarm_upmax)
      u8g2_DrawUTF8(&u8g2, 20, 31, "芯片温度过高！");
    if (sw35xx_c1.state.tem_shutdown)
      u8g2_DrawUTF8(&u8g2, 20, 31, "高温关机保护！");
    if (sw35xx_c1.state.short_citcuit)
      u8g2_DrawUTF8(&u8g2, 20, 31, "输出短路！"); // 0x05版本的芯片貌似不能用
    u8g2_DrawUTF8(&u8g2, 0, 47, "C2异常代码");
    u8g2_DrawUTF8(&u8g2, 20, 63, "系统无故障");
    if (sw35xx_c2.state.val_input_upmax)
      u8g2_DrawUTF8(&u8g2, 20, 63, "输入电压过高！");
    if (sw35xx_c2.state.tem_alarm_upmax)
      u8g2_DrawUTF8(&u8g2, 20, 63, "芯片温度过高！");
    if (sw35xx_c2.state.tem_shutdown)
      u8g2_DrawUTF8(&u8g2, 20, 63, "高温关机保护！");
    if (sw35xx_c2.state.short_citcuit)
      u8g2_DrawUTF8(&u8g2, 20, 63, "输出短路！"); // 0x05版本的芯片貌似不能用

**Comment by Inevitableofcold** [comment]
感谢回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liaozhelin/yds-charger"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月3日(星期三) 晚上9:52
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [liaozhelin/yds-charger] 问下电压电流异常充电站会这么显示，发出什么样的报警？ (Issue #70)





 
uint8_t event = u8x8_GetMenuEvent(u8g2_GetU8x8(&amp;u8g2));
 u8g2_ClearBuffer(&amp;u8g2);
 u8g2_DrawUTF8(&amp;u8g2, 0, 15, "C1异常代码");
 u8g2_DrawUTF8(&amp;u8g2, 20, 31, "系统无故障");
 if (sw35xx_c1.state.val_input_upmax)
 u8g2_DrawUTF8(&amp;u8g2, 20, 31, "输入电压过高！");
 if (sw35xx_c1.state.tem_alarm_upmax)
 u8g2_DrawUTF8(&amp;u8g2, 20, 31, "芯片温度过高！");
 if (sw35xx_c1.state.tem_shutdown)
 u8g2_DrawUTF8(&amp;u8g2, 20, 31, "高温关机保护！");
 if (sw35xx_c1.state.short_citcuit)
 u8g2_DrawUTF8(&amp;u8g2, 20, 31, "输出短路！"); // 0x05版本的芯片貌似不能用
 u8g2_DrawUTF8(&amp;u8g2, 0, 47, "C2异常代码");
 u8g2_DrawUTF8(&amp;u8g2, 20, 63, "系统无故障");
 if (sw35xx_c2.state.val_input_upmax)
 u8g2_DrawUTF8(&amp;u8g2, 20, 63, "输入电压过高！");
 if (sw35xx_c2.state.tem_alarm_upmax)
 u8g2_DrawUTF8(&amp;u8g2, 20, 63, "芯片温度过高！");
 if (sw35xx_c2.state.tem_shutdown)
 u8g2_DrawUTF8(&amp;u8g2, 20, 63, "高温关机保护！");
 if (sw35xx_c2.state.short_citcuit)
 u8g2_DrawUTF8(&amp;u8g2, 20, 63, "输出短路！"); // 0x05版本的芯片貌似不能用
