### ISSUE TITLE
RGB灯和屏幕都点不亮 求大佬看看

### ISSUE THREAD

**Issue by 1075081239** [liaozhelin/yds-charger#72]
刷写固件后两个A口可以正常充电，但是RGB灯和屏幕都不亮，请问可能是什么原因

**Comment by blacksr** [comment]
C口能正常输出吗，先确认32是不是正常跑起来了，（程序如果烧进去的话应该是跑起来了）
屏幕的话电容如果上错了是没法点亮的，检查一下原理图和实际上的料，对着原理图打一下屏幕排线那边的电压是不是正常的；
RGB灯应该好解，量一下4脚有没有3.3，3脚到32芯片的9脚是不是通的就行；
你这里都是到32芯片的问题，估计是32没焊接好，后面A口不需要32芯片也能工作，如果C口没有输出的话加焊一下32芯片试试
