### ISSUE TITLE
电脑找不到芯片，是没装驱动吗？

### ISSUE THREAD

**Issue by Zhangyucong0210** [liaozhelin/yds-charger#73]
希望大佬能提供一下驱动

**Comment by 1075081239** [comment]
这个需要将拨码开关左拨（作者readme中的方向）再上电，进入BOOT模式，可以看到串口com*，这个应该不需要驱动的

**Comment by blacksr** [comment]
电脑设备管理器有识别到东西吗，任意都可以，如果没有的话建议检查一下最小系统里的焊接和原件是否上错，另外建议把32芯片加焊一下，风枪吹QFN封装还是很容易虚焊的

**Comment by Zhangyucong0210** [comment]
大佬们能提供一下项目里分立下载的bin文件吗，没找到独立的bin文件，我驯化ESPIDF失败了，合并下载的bin文件好像功能很少。只有个气象站？

**Comment by blacksr** [comment]
- #33 
这个issue里分享的固件功能比较多更新的也比较勤，OTA功能也有

**Comment by Els1314** [comment]
拨码通电后只有串口多了2个JTAG，端口COM没有反应，是什么回事？

**Comment by blacksr** [comment]
> 拨码通电后只有串口多了2个JTAG，端口COM没有反应，是什么回事？

有图片吗，设备管理器截个图看一下可能需要安装驱动

**Comment by Els1314** [comment]
拨码通电后只有串口多了2个JTAG，端口COM没有反应，是什么回事？

**Comment by liaozhelin** [comment]
能检测到jtag应该问题不大，大概率还是驱动问题

**Comment by a1659746547** [comment]
> 电脑设备管理器有识别到东西吗，任意都可以，如果没有的话建议检查一下最小系统里的焊接和原件是否上错，另外建议把32芯片加焊一下，风枪吹QFN封装还是很容易虚焊的
> 
> Computer Device Manager recognize anything? If not, it is recommended to check the minimum system welding and the original is wrong, and it is recommended to add the 32 chip welding, air Gun blowing QFN package is easy to solder

接入后在com有提示未知设备是正常的吗。晶振电容我使用20pf代替有无影响的？求解答

**Comment by a1659746547** [comment]
> 电脑设备管理器有识别到东西吗，任意都可以，如果没有的话建议检查一下最小系统里的焊接和原件是否上错，另外建议把32芯片加焊一下，风枪吹QFN封装还是很容易虚焊的

接入后在com有提示未知设备是正常的吗。晶振电容我使用20pf代替有无影响的？求解答

**Comment by a1659746547** [comment]
> > 电脑设备管理器有识别到东西吗，任意都可以，如果没有的话建议检查一下最小系统里的焊接和原件是否上错，另外建议把32芯片加焊一下，风枪吹QFN封装还是很容易虚焊的
> 
> 接入后在com有提示未知设备是正常的吗。晶振电容我使用20pf代替有无影响的？求解答
![Snipaste_2022-09-05_14-20-53](https://user-images.githubusercontent.com/80776953/188373438-94527c74-e16b-4dff-aaf6-d954c48823d9.png)

**Comment by a1659746547** [comment]
> 这个需要将拨码开关左拨（作者readme中的方向）再上电，进入BOOT模式，可以看到串口com*，这个应该不需要驱动的

这个是必须的嘛

**Comment by blacksr** [comment]
> > 这个需要将拨码开关左拨（作者readme中的方向）再上电，进入BOOT模式，可以看到串口com*，这个应该不需要驱动的
> 
> 这个是必须的嘛

对的 进入bootmode是必须将拨码开关左拨然后再上电的



> > 电脑设备管理器有识别到东西吗，任意都可以，如果没有的话建议检查一下最小系统里的焊接和原件是否上错，另外建议把32芯片加焊一下，风枪吹QFN封装还是很容易虚焊的
> 
> 接入后在com有提示未知设备是正常的吗。晶振电容我使用20pf代替有无影响的？求解答

电路原理我不是很懂，所以电容不一样我不清楚；
如果有显示未知设备的话可以试着装一下驱动先，驱动文件在仓库里是有的；

**Comment by shileinuo** [comment]
库里的驱动不支持win10啊，还有没其它链接我也装不上驱动，识别不到com

**Comment by Zhangyucong0210** [comment]
可能是焊接有问题
&nbsp;


张聿璁
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月20日(星期四) 下午3:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liaozhelin/yds-charger] 电脑找不到芯片，是没装驱动吗？ (Issue #73)





 
库里的驱动不支持win10啊，还有没其它链接我也装不上驱动，识别不到com

**Comment by blacksr** [comment]
> 库里的驱动不支持win10啊，还有没其它链接我也装不上驱动，识别不到com

有识别出东西嘛，识别到了才能装驱动，你是怎么安装的驱动呢

**Comment by shileinuo** [comment]
![188373438-94527c74-e16b-4dff-aaf6-d954c48823d9](https://user-images.githubusercontent.com/114798097/196899190-690ec79e-1500-475e-9c20-6ebead7f383c.png)

**Comment by shileinuo** [comment]
拨盘上电识别出未知USB设备，装了两块板子都这样

**Comment by blacksr** [comment]
> 拨盘上电识别出未知USB设备，装了两块板子都这样

右键选inf文件进行安装装不上吗

**Comment by shileinuo** [comment]
选inf 文件安装提示不是为X64系统兼容的

**Comment by shileinuo** [comment]
![43cc19de47e9ccbbb5decad2706688e](https://user-images.githubusercontent.com/114798097/196926555-85940202-e595-492c-b5d9-621226013e3e.png)

**Comment by blacksr** [comment]
> ![43cc19de47e9ccbbb5decad2706688e](https://user-images.githubusercontent.com/114798097/196926555-85940202-e595-492c-b5d9-621226013e3e.png)

你电脑系统不是64位的吗

**Comment by shileinuo** [comment]
就是win10 64位专业版啊 所以安装不上奇怪啊，用的是作者固件压缩包里的驱动。。

**Comment by shileinuo** [comment]
或者你发一份驱动我试试呗 183445831@qq.com  感谢

**Comment by shileinuo** [comment]
永远找到原因了，奶奶个熊！买的是无源40m晶振发来是有源的！没仔细看。。。。
