### ISSUE TITLE
请问采购原件是以bom为准吗？

### ISSUE THREAD

**Issue by NereeScarlet** [liaozhelin/yds-charger#74]
采购指南里面的图片和bom里面的参数似乎有一些对不上的地方，然后位号似乎也有对不上的地方（在下是个真小白，如果是有什么不清楚的地方说错了还请原谅QAQ）
像是C1,C4,C44,C61,C65这几个看bom里面都是一种类型的原件，然而采购指南里面c1、c44是一种用的是那个直插固态电容， C59,C60,C4,C65,C61 又是另外一种，用的是那个高频低阻直插铝电解电容。
就是那个……到底是以哪个为准啊QAQ求求大佬救救孩子吧，再有不到俩月在下妹妹生日就到了，QAQ

**Comment by shui136** [comment]
可以按照github仓库中 hardware/采购指南.md 的购买
https://github.com/liaozhelin/yds-charger/blob/main/1.Hardware/%E5%99%A8%E4%BB%B6%E9%87%87%E8%B4%AD%E6%8C%87%E5%8D%97.md

**Comment by NereeScarlet** [comment]
但是问题是bom现在似乎和采购指南出现了一些不同之处啊……

**Comment by blacksr** [comment]
#64 
几个插件电容可以参考这个Issue

其实没有要求一定要买什么样的，实在不行就全上固态电容就行；
其他的电容没标的买50V的就肯定没错，标了电压的就按照电压买就行，精度有钱就上好的没有就1% 5%的都可以，有一些非标电阻买不到的话我买的近似阻值容值都是能够正常工作的，直接立创一站配齐就行，一些特殊料或者比较贵（比如屏幕）的料就去淘宝买；
关于屏幕购买注意不要买错了，我就是买错了，淘宝上有两家店，卖的同样的型号，尺寸却不一样，详见这个issue：
#39 
#26 
这两篇issue里面有讨论屏幕尺寸问题的

**Comment by NereeScarlet** [comment]
> * [大佬你好，请问能否出一个顶层无电容钻孔的版本？ #64](https://github.com/liaozhelin/yds-charger/issues/64)
> 
> 几个插件电容可以参考这个Issue
> 
> 其实没有要求一定要买什么样的，实在不行就全上固态电容就行，电压和容值对的上就好了； 其他的电容没标的买50V的就肯定没错，标了电压的就按照电压买就行，精度有钱就上好的没有就1% 5%的都可以，有一些非标电阻买不到的话我买的近似阻值容值都是能够正常工作的，直接立创一站配齐就行，一些特殊料或者比较贵（比如屏幕）的料就去淘宝买； 关于屏幕购买注意不要买错了，我就是买错了，淘宝上有两家店，卖的同样的型号，尺寸却不一样，详见这个issue：
> 
> * [屏幕有合适的吗 #39](https://github.com/liaozhelin/yds-charger/issues/39)
> * [显示屏接线相关优化 #26](https://github.com/liaozhelin/yds-charger/issues/26)
> 
> 这两篇issue里面有讨论屏幕尺寸问题的

非常感谢！！！
