### ISSUE TITLE
板子发生了一件很离谱的事，求解决

### ISSUE THREAD

**Issue by 1075081239** [liaozhelin/yds-charger#75]
焊接好后接5V电压，RY8411一直输出0.97V左右，找了很久没找到原因，接上12V后冒出了一点点黑烟，然后就正常输出3.3V了，再接上5V也是正常输出3.3V，求大佬看看什么原因，附上板子照片如下
![IMG_20220814_122122](https://user-images.githubusercontent.com/33981454/184522424-cced7de7-2bb1-4aba-9ba7-acfb6e613c72.jpg)

**Comment by mornlena** [comment]
肯定之前3.3v输出后面有短路啊，烧掉了短路，就正常了，查找焊接吧

**Comment by liaozhelin** [comment]
是的，应该是某些地方短路了
