### ISSUE TITLE
请问BOM表中的贴片阻容器件选型，电压功率要求，电容16V，电阻0.1W是否够用

### ISSUE THREAD

**Issue by yrjaycn** [liaozhelin/yds-charger#76]
由于专业知识限制，无力分析电路图中各点位的电压电流，特咨询
BOM表中除少量特别标注了型号的物料，在选型时遇到困扰
电容物料：除少量有标注电压的，其他物料用16V规格的贴片电容是否够用。
电阻物料：BOM表中没有标注功率要求，看0.1W的物料最通用，请问0.1W的功率规格是否够用，是否有需要提高规格的点位
以上咨询，感谢回复
tks

**Comment by liaozhelin** [comment]
除了采样电阻，其他功率无所谓，主线上的贴片电容用35v的比较好
