### ISSUE TITLE
两个C口均显示0.00V 0.00A

### ISSUE THREAD

**Issue by wd5457** [liaozhelin/yds-charger#79]
最初的问题是两个A口正常，C1口正常，C2口空载显示5V且无法快充，拨轮开关无效。
重新焊接SW3526后两个C口都显示0.00V 0.00A且无法工作，应该不是SW3526焊接的问题，更换了新的并重新焊接了几次都是这样，还可能有什么原因呢？

**Comment by mornlena** [comment]
电压，电流是通过i2c总线读取数据的，空载的情况，电压应该有个0.03左右的底数，没有的话就说明sw3526和esp32主芯片之间的通讯有问题，焊接是一方面， 芯片损坏也是有可能的！具体到无法快充，要检查c口的cc1，cc2 和dp这几条线和sw3526的连接，也涉及到焊接问题，仔细检查吧，电路没问题，很多人验证过了！

**Comment by liaozhelin** [comment]
是的，跟着上面大佬们说的做就可以
