### ISSUE TITLE
固件下载进去没显示，led也没亮

### ISSUE THREAD

**Issue by X131402** [liaozhelin/yds-charger#8]
固件是按图片设置下载的，但是我做了三个都没显示，输出全部都正常，不知道是哪里的问题？🥹

**Comment by liaozhelin** [comment]
> 固件是按图片设置下载的，但是我做了三个都没显示，输出全部都正常，不知道是哪里的问题？🥹

你好，我复查后发现是第一次提交的教程，有个bin文件的地址有错误，我现在提交了合并版本的固件，已经在我的电脑上验证了教程，可以通过烧录合并固件，直接烧录一个即可，详细说明可以见更新后的Readme。目前固件功能是第一屏还有设置界面，第二界面的天气显示还在开发中，第三界面预留，第四界面是设置界面，可以通过后面的拨动按键切换。如果制作成功也可以在issue中反馈下，给其他人参考😘

**Comment by X131402** [comment]
你好，屏幕有显示了，但是卡在wifi网络初始化就不动了，这个是哪里的问题呀。下载的是整合固件

**Comment by liaozhelin** [comment]
> 你好，屏幕有显示了，但是卡在wifi网络初始化就不动了，这个是哪里的问题呀。下载的是整合固件
wifi初始化后是提示OK还是ER?

**Comment by X131402** [comment]
就是屏幕显示到最后一条wifi网络初始化... ，就不动了，进不了主页面，然后也没显示OK和ER，就卡在那里

**Comment by liaozhelin** [comment]
> 好的，谢谢了

你好，已经提交修复版本的固件，你烧录后看看，应该初次是会提示NO，然后后面开关向右拨动四次进入设置界面，选择 **无线配置-配网** 然后再用手机的esptouch软件给设备配网，配网成功后手机会提示设备也会自动退出配网状态，SSID和密码也会存储在设备中，重新上电后应该就会提示OK了

**Comment by X131402** [comment]
已经可以了，联网也正常，谢谢!

**Comment by X131402** [comment]
感谢！！
