### ISSUE TITLE
可以提出硬件功能的建议吗

### ISSUE THREAD

**Issue by guougopeng** [liaozhelin/yds-charger#84]
非常喜欢UP主这个四路独立芯片的设计，这几乎正是我需要的充电器。但是还是希望UP主能在未来的改进中提供一个100W的C口方便给笔记本供电，如果这个C口能提供升压功能就更好了，方便12V供电。虽然现在电路板元件已经很密集了，但还是希望UP主能够考虑我提出的建议。谢谢啦

**Comment by Zyilin98** [comment]
升压是真的没地方做了 100W的chip可能需要外置mos 电感大小也会更大 可能当前的外壳放不下

**Comment by Foxzc** [comment]
PD支持100W就完美了

**Comment by Inevitableofcold** [comment]
急收5.5x2.1 至少140W笔记本电源 可以正常给充电站使用的 v 13950722089 可以走咸鱼
