### ISSUE TITLE
识别到设备但无法烧录

### ISSUE THREAD

**Issue by blacksr** [liaozhelin/yds-charger#9]
dalao你好
![111](https://user-images.githubusercontent.com/43858966/173400912-f6f2e224-d840-4f4d-9b79-c0b2f30d52eb.png)
！
使用外部的电源给的3.3，GND和USB的GND共在一起了，识别出设备后烧录时报了以上的错误，波特率1152000和115200都试了都不行，请问是什么原因可能导致的呢
以下是我遇到的一些问题
1、我将元件焊接完成后DC给了5V测量了RY8411输出是3.6V左右，但DC给24V后RY8411输出就是3.3V了，这部分会影响吗
2、电脑识别时会识别出来然后断开再识别再断开，反复不断，此时3.3V供电电流大约是16mA左右，将拨动开关往左拨进入bootmode后就能正常识别了，此时电流大约是20mA左右，请问这样的现象是正常的吗

**Comment by blacksr** [comment]
好的好的谢谢解答！
1、电压正常的话我就放心了
2、如果下载模式指的是拉住拨动开关后上电的话，那么我的操作应该是没有问题的，进入了下载模式后就不会断连了，不进入就会，我还没有尝试烧录完成后还会不会断连【因为烧录不进去:(】芯片我刚刚确认了一下，应该是买错了，没有带尾缀FN4
这个是我买的物料链接，看起来是买错了的
https://item.szlcsc.com/3013220.html

**Comment by liaozhelin** [comment]
> 好的好的谢谢解答！
> 
> 1、电压正常的话我就放心了
> 
> 2、如果下载模式指的是拉住拨动开关后上电的话，那么我的操作应该是没有问题的，进入了下载模式后就不会断连了，不进入就会，我还没有尝试烧录完成后还会不会断连【因为烧录不进去:(】芯片我刚刚确认了一下，应该是买错了，没有带尾缀FN4
> 
> 这个是我买的物料链接，看起来是买错了的
> 
> https://item.szlcsc.com/3013220.html

是的，ESP32C3物料购买错误这个是我前期的BOM中的疏忽导致的，lceda最开始导出BOM时候去掉了备注栏，没有注明flash版本，前几天已经修订了BOM中器件型号和更新了说明文件，价格上的话应该贵个2元左右

**Comment by blacksr** [comment]
另外我使用了PD测试仪测了一下，虽然没有烧录，USBA口其实已经开始工作了，能够测的出来协议了，不过USBC就还不行:)

**Comment by liaozhelin** [comment]
> 另外我使用了PD测试仪测了一下，虽然没有烧录，USBA口其实已经开始工作了，能够测的出来协议了，不过USBC就还不行:)

USBC的sw3526应该是要等esp32烧完程序后，i2c配置使能后才可以工作，应该是没有问题

**Comment by blacksr** [comment]
更换了32芯片之后就好了！感谢dalao分享的方案！

**Comment by blacksr** [comment]
![362b704f616e5db74143f567045bebc](https://user-images.githubusercontent.com/43858966/173986216-b94961d0-33f6-482d-9073-c15505ca9c9f.jpg)
![c9c4e3c4199b5d194d2899b2a7d3ff6](https://user-images.githubusercontent.com/43858966/173986231-42ee599a-a047-4099-b78b-a86b912ff31b.jpg)
![62ab9792c1e04a43d454e6ac0a0adb1](https://user-images.githubusercontent.com/43858966/173986236-5d2b0cfe-0546-4a7e-be7f-ff6a9e1bda65.jpg)
![8dde76b2d77bc9eb0766a4ee2df1e12](https://user-images.githubusercontent.com/43858966/173986237-dbd2383f-6ca1-4f91-be7d-aaff0ccd9431.jpg)
![1da567bd822ba085dfa0cdc5e4b687a](https://user-images.githubusercontent.com/43858966/173986242-467d73a8-4035-46e1-817f-f28720df9608.jpg)
![fd24eae8fd9351b7fb25858ac8736ee](https://user-images.githubusercontent.com/43858966/173986247-3e9ea8dd-21f4-47b5-a428-9a3715615f8b.jpg)
![afa2d1aed28b93229857d2441a203f9](https://user-images.githubusercontent.com/43858966/173986251-0c54447d-e5dc-4c55-941f-cf41545f1c6c.jpg)

**Comment by blacksr** [comment]
外壳打算3d打印一个看一下，满载跑一下老化看看温度，要是温度高搞个铝壳底板打印外壳

**Comment by liaozhelin** [comment]
不推荐3D打印，散热挺差的，pla肯定会变形，铝壳也不贵，而且还有前后螺丝

**Comment by blacksr** [comment]
不行就底板改用铝板加导热贴，3D打印只是外形而已，或者说先用3D打印机验证模型尺寸后面直接CNC一块板子出来，CNC可以薅公司的用一下，打印机我倒是自己有

**Comment by liaozhelin** [comment]
原来是有cnc的dalao，那就更舒服了，可以说上下铣些散热沟槽，高功率下应该会更稳定

**Comment by blacksr** [comment]
散热还是挺重要的，毕竟我给笔记本充电的话65W是得吃满的，主要是觉得那个通用外壳有点捞
